select * from customers


--'customer_id', 'age', 'gender', 'item_purchased', 'category',
       --'purchase_amount', 'location', 'size', 'color', 'season',
       --'review_rating', 'subscription_status', 'shipping_type',
       --'discount_applied', 'previous_purchases', 'payment_method',
       --'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
     -- dtype='object'

--Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, SUM(purchase_amount) AS revenue
FROM customers
GROUP BY gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM customers
WHERE discount_applied = 'yes'
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customers);



-- Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5 
    item_purchased, 
    ROUND(CAST(AVG(review_rating) AS DECIMAL(10,2)), 2) AS [Average Product Rating]
FROM customers
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type,ROUND(CAST(AVG(purchase_amount) AS DECIMAL(10,2)), 2) as avg from customers
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status,
count(customer_id) as total_customers,
ROUND(CAST(AVG(purchase_amount) AS DECIMAL(10,2)), 2) as avg,
ROUND(CAST(sum(purchase_amount) AS DECIMAL(10,2)), 2) as total_revenue from customers
group by subscription_status
order by sum(purchase_amount),AVG(purchase_amount) desc


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT TOP 5
    item_purchased,
    ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as 
(
select customer_id,previous_purchases,
case when previous_purchases = 1 then 'new'
     when previous_purchases between 2 and 10 then 'returning'
     when previous_purchases >10 then 'loyal' end as customer_segment 
     from customers
)
select customer_segment,count(*) as number_of_customers from customer_type
group by customer_segment
order by count(*) desc;

--Q8. What are the top 3 most purchased products within each category? 

select item_rnk,category,item_purchased, total_orders from
(
select item_purchased,category,count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rnk from customers
group by category,item_purchased 
)a
where a.item_rnk<=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group? 

SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue desc;